CREATE TABLE igcmts (  mtu CHAR(17),  mtname VARCHAR(200) NULL,  mdate BIGINT NOT NULL,  pstatus CHAR(1) NULL,  a1 VARCHAR(50) NULL,  a2 VARCHAR(200) NULL);
CREATE UNIQUE INDEX idx_igcmts_f1 ON igcmts(mtname);
CREATE TABLE igcappoption (  mts CHAR(17) NOT NULL,  optype VARCHAR(20) NULL,  pstatus INTEGER NULL,  seq INTEGER NULL,  content VARCHAR(1000),  mdate BIGINT NULL);
CREATE INDEX idx_igcappoption_tenant ON igcappoption(mts);
CREATE TABLE igcdatapools (  iuid CHAR(17) NULL,  pname VARCHAR(100) NULL,  pstatus INTEGER NULL,  mdate BIGINT NULL);
CREATE UNIQUE INDEX idx_igcdatapools_f1 ON igcdatapools(iuid);
CREATE TABLE igcdepts (  mts CHAR(17) NOT NULL,  gid CHAR(17) NOT NULL,  dname VARCHAR(100) NULL,  active INTEGER NULL,  mdate BIGINT NULL,  pid CHAR(17) NULL,  node VARCHAR(1000),  mid CHAR(17) NULL,  description VARCHAR(1000),  dtype CHAR(1) DEFAULT 'A',  privilege VARCHAR(100) NULL,  lacc INTEGER DEFAULT 0,  cacc INTEGER DEFAULT 0,  dept_id VARCHAR(20) NULL,  ssomod VARCHAR(20) NULL,  ssodsr VARCHAR(20) NULL);
CREATE INDEX idx_igcdepts_f1 ON igcdepts(gid);
CREATE INDEX idx_igcdepts_f2 ON igcdepts(pid);
CREATE INDEX idx_igcdepts_f3 ON igcdepts(mid);
CREATE INDEX idx_igcdepts_tenant ON igcdepts(mts);
CREATE TABLE igcdlog (  mts CHAR(17) NOT NULL,  iuid CHAR(17) NULL,  userid VARCHAR(50) NULL,  mid CHAR(17) NULL,  eid CHAR(17) NULL,  rcpt VARCHAR(255) NULL,  cname VARCHAR(255) NULL,  mctype INTEGER NULL,  content VARCHAR(1000),  pstatus INTEGER NULL,  seq INTEGER NULL,  description VARCHAR(1000),  mdate BIGINT NULL,  title VARCHAR(255) NULL,  orig_title VARCHAR(255) NULL,  message VARCHAR(1000),  orig_message VARCHAR(1000),  userseq INTEGER NULL,  allrcpt VARCHAR(1000));
CREATE INDEX idx_igcdlog_f1 ON igcdlog(iuid);
CREATE INDEX idx_igcdlog_f2 ON igcdlog(mid);
CREATE INDEX idx_igcdlog_f3 ON igcdlog(eid);
CREATE INDEX idx_igcdlog_f4 ON igcdlog(cname);
CREATE INDEX idx_igcdlog_tenant ON igcdlog(mts);
CREATE TABLE igcduty (  mts CHAR(17) NOT NULL,  sid CHAR(17) NULL,  dname VARCHAR(100) NULL,  pstatus INTEGER NULL,  dutytype CHAR(1) NULL,  mdate BIGINT NULL,  description VARCHAR(1000),  node VARCHAR(1000),  ssomod VARCHAR(20) NULL,  ssodsr VARCHAR(20) NULL);
CREATE UNIQUE INDEX idx_igcduty_f1 ON igcduty(sid, mts);
CREATE INDEX idx_igcduty_tenant ON igcduty(mts);
CREATE TABLE igcelog (  lid CHAR(17) NULL,  userid VARCHAR(50) NULL,  iuid CHAR(17) NULL,  mid CHAR(17) NULL,  mname VARCHAR(255) NULL,  node VARCHAR(255) NULL,  exectime VARCHAR(100),  mdate BIGINT NULL,  pstatus INTEGER NULL);
CREATE TABLE igcerror (  errorcode INTEGER NOT NULL,  description VARCHAR(1000),  detail VARCHAR(1000));
CREATE UNIQUE INDEX idx_igcerror_f1 ON igcerror(errorcode);
CREATE TABLE igcfab (  mts CHAR(17) NOT NULL,  iuid CHAR(17) NULL,  pid CHAR(17) NULL,  mdate BIGINT NULL,  fatype CHAR(1) NULL);
CREATE INDEX idx_igcfab_f1 ON igcfab(iuid);
CREATE INDEX idx_igcfab_f2 ON igcfab(pid);
CREATE INDEX idx_igcfab_f3 ON igcfab(mdate);
CREATE INDEX idx_igcfab_tenant ON igcfab(mts);
CREATE TABLE igcgeo (  loctype CHAR(3) NULL,  loccode CHAR(10) NULL,  ploc VARCHAR(100) NULL,  sloc VARCHAR(100) NULL,  lat FLOAT NULL,  lng FLOAT NULL,  geoloctype INTEGER NULL,  bndlatsw FLOAT NULL,  bndlngsw FLOAT NULL,  bndlatne FLOAT NULL,  bndlngne FLOAT NULL);
CREATE INDEX idx_igcgeo_f1 ON igcgeo(loccode);
CREATE TABLE igchelp (  pid CHAR(10) NULL,  lang CHAR(6) DEFAULT 'EN',  title VARCHAR(255) NULL,  hctype INTEGER NULL,  content VARCHAR(1000),  pstatus INTEGER NULL,  seq INTEGER NULL,  mdate BIGINT NULL);
CREATE INDEX idx_igchelp_f1 ON igchelp(pid);
CREATE TABLE igcinst (  iuid CHAR(17) NULL,  mid CHAR(17) NULL,  iid CHAR(17) NULL,  rptname VARCHAR(255) NULL,  content VARCHAR(1000),  seq INTEGER NULL,  mdate BIGINT NULL,  cdate BIGINT NULL);
CREATE INDEX idx_igcinst_f1 ON igcinst(iuid);
CREATE INDEX idx_igcinst_f2 ON igcinst(mid);
CREATE INDEX idx_igcinst_f3 ON igcinst(iid);
CREATE INDEX idx_igcinst_f4 ON igcinst(mdate);
CREATE TABLE igcinstl (  iuid CHAR(17) NULL,  mid CHAR(17) NULL,  iid CHAR(17) NULL,  rptname VARCHAR(255) NULL,  mdate BIGINT NULL,  cdate BIGINT NULL,  laccdate INTEGER NULL,  lacctime INTEGER NULL,  ilstatus INTEGER NULL,  laccs INTEGER NULL,  mts CHAR(17) NULL);
CREATE INDEX idx_igcinstl_f1 ON igcinstl(iuid);
CREATE INDEX idx_igcinstl_f2 ON igcinstl(mid);
CREATE INDEX idx_igcinstl_f3 ON igcinstl(iid);
CREATE INDEX idx_igcinstl_f4 ON igcinstl(mdate);
CREATE TABLE igclexp (  iuid CHAR(17) NULL,  mid CHAR(17) NULL,  mdate BIGINT NULL,  luid CHAR(17) NULL,  lname VARCHAR(255) NULL,  pstatus INTEGER NULL,  fext VARCHAR(10) NULL);
CREATE INDEX idx_igclexp_f1 ON igclexp(iuid);
CREATE INDEX idx_igclexp_f2 ON igclexp(mid);
CREATE INDEX idx_igclexp_f3 ON igclexp(mdate);
CREATE TABLE igclimp (  iuid CHAR(17) NULL,  mdate BIGINT NULL,  luid CHAR(17) NULL,  lname VARCHAR(255) NULL,  pstatus INTEGER NULL,  fext VARCHAR(10) NULL,  mid CHAR(17, file_bin BLOB NULL) NULL);
CREATE INDEX idx_igclimp_f1 ON igclimp(iuid);
CREATE INDEX idx_igclimp_f3 ON igclimp(mdate);
CREATE TABLE igclu (  mts CHAR(17) NOT NULL,  iuid CHAR(17) NULL,  pstatus INTEGER NULL,  mdate BIGINT NULL,  mid CHAR(17) NULL);
CREATE INDEX idx_igclu_f1 ON igclu(iuid);
CREATE INDEX idx_igclu_f2 ON igclu(mid);
CREATE INDEX idx_igclu_tenant ON igclu(mts);
CREATE TABLE igcserver (  pname VARCHAR(100) NULL,  content VARCHAR(200),  mdate BIGINT NULL);
CREATE TABLE igcms (  mts CHAR(17) NOT NULL,  iuid CHAR(17) NULL,  pid CHAR(17) NULL,  mctype INTEGER NULL,  cname VARCHAR(100) NULL,  mdate BIGINT NULL,  pstatus INTEGER NOT NULL,  node VARCHAR(1000),  description VARCHAR(1000),  memo VARCHAR(100) NULL,  sid CHAR(17),  mid CHAR(17),  objinfo VARCHAR(500) NULL,  revise INTEGER NOT NULL,  mrevise INTEGER NOT NULL,  trid CHAR(17) NULL,  qdes VARCHAR(100) NULL,  attrb1 VARCHAR(100) NULL,  attrb2 VARCHAR(100) NULL,  attrb3 VARCHAR(100) NULL,  attrb4 VARCHAR(100) NULL,  attrb5 VARCHAR(100) NULL,  is_sub INTEGER NOT NULL);
CREATE INDEX idx_igcms_f1 ON igcms(iuid);
CREATE UNIQUE INDEX idx_igcms_f2 ON igcms(pid, cname, mts, pstatus);
CREATE UNIQUE INDEX idx_igcms_f3 ON igcms(iuid, pstatus, mts);
CREATE INDEX idx_igcms_f4 ON igcms(cname);
CREATE INDEX idx_igcms_f5 ON igcms(pid);
CREATE INDEX idx_igcms_f6 ON igcms(mctype);
CREATE INDEX idx_igcms_f7 ON igcms(memo, iuid);
CREATE INDEX idx_igcms_tenant ON igcms(mts);
CREATE TABLE igcmcc (  mts CHAR(17) NOT NULL,  iuid CHAR(17) NULL,  seq INTEGER NOT NULL,  mctype INTEGER NULL,  mdate BIGINT NULL,  content VARCHAR(1000),  revise INTEGER NOT NULL,  description VARCHAR(1000),  sid CHAR(17));
CREATE INDEX idx_igcmcc_f1 ON igcmcc(iuid);
CREATE UNIQUE INDEX idx_igcmcc_f2 ON igcmcc(iuid, revise, seq, mts);
CREATE INDEX idx_igcmcc_tenant ON igcmcc(mts);
CREATE TABLE igcmce (  mts CHAR(17) NOT NULL,  iuid CHAR(17) NULL,  seq INTEGER NOT NULL,  mctype INTEGER NOT NULL,  mdate BIGINT NULL,  content VARCHAR(1000),  revise INTEGER NOT NULL,  description VARCHAR(1000),  sid CHAR(17));
CREATE INDEX idx_igcmce_f1 ON igcmce(iuid);
CREATE UNIQUE INDEX idx_igcmce_f2 ON igcmce(iuid, revise, seq, mts);
CREATE INDEX idx_igcmce_tenant ON igcmce(mts);
CREATE TABLE igcobjectauth (  mts CHAR(17) NOT NULL,  sid CHAR(17) NULL,  iuid CHAR(17) NULL,  writable CHAR(1) DEFAULT 'N',  c_manage CHAR(1) DEFAULT 'F');
CREATE INDEX idx_igcobjectauth_f1 ON igcobjectauth(iuid);
CREATE INDEX idx_igcobjectauth_f2 ON igcobjectauth(sid);
CREATE INDEX idx_igcobjectauth_tenant ON igcobjectauth(mts);
CREATE TABLE igcrelation (  iuid CHAR(17) NULL,  rid CHAR(17) NULL,  mdate BIGINT NULL,  pstatus INTEGER NULL,  rtype INTEGER NULL,  utype INTEGER NULL);
CREATE INDEX idx_igcrelation_f1 ON igcrelation(iuid);
CREATE INDEX idx_igcrelation_f2 ON igcrelation(rid);
CREATE TABLE igcslog (  mts CHAR(17) NOT NULL,  iuid CHAR(17) NULL,  userid VARCHAR(50) NULL,  mid CHAR(17) NULL,  eid CHAR(17) NULL,  cname VARCHAR(255) NULL,  mctype INTEGER NULL,  content VARCHAR(1000),  pstatus INTEGER NULL,  seq INTEGER NULL,  description VARCHAR(1000),  mdate BIGINT NULL,  title VARCHAR(255) NULL,  message VARCHAR(1000));
CREATE INDEX idx_igcslog_f1 ON igcslog(iuid);
CREATE INDEX idx_igcslog_f2 ON igcslog(mid);
CREATE INDEX idx_igcslog_f3 ON igcslog(eid);
CREATE INDEX idx_igcslog_tenant ON igcslog(mts);
CREATE TABLE igcsnap (  iuid CHAR(17) NULL,  mid CHAR(17) NULL,  eid CHAR(17) NULL,  cname VARCHAR(255) NULL,  mctype INTEGER NULL,  content VARCHAR(1000),  execcontent VARCHAR(1000),  pstatus INTEGER NULL,  seq INTEGER NULL,  description VARCHAR(1000),  mdate BIGINT NULL);
CREATE INDEX idx_igcsnap_f1 ON igcsnap(iuid);
CREATE INDEX idx_igcsnap_f2 ON igcsnap(mid);
CREATE INDEX idx_igcsnap_f3 ON igcsnap(eid);
CREATE TABLE igcstatus (  pstatus INTEGER NULL,  description VARCHAR(128) NULL,  STYPE INTEGER NULL);
CREATE TABLE igcsystemlogs (  lid CHAR(17) NULL,  LTYPE INTEGER NULL,  content VARCHAR(1000),  mdate BIGINT NULL);
CREATE UNIQUE INDEX idx_igcsystemlogs_f1 ON igcsystemlogs(lid);
CREATE TABLE igctables (  iuid CHAR(17) NULL,  pid CHAR(17) NULL,  mctype INTEGER NULL,  seq INTEGER NULL,  tname VARCHAR(100) NULL,  mdate BIGINT NULL,  content VARCHAR(1000) NULL,  pstatus INTEGER NULL);
CREATE INDEX idx_igctables_f1 ON igctables(iuid);
CREATE INDEX idx_igctables_f2 ON igctables(pid);
CREATE INDEX idx_igctables_f3 ON igctables(mctype);
CREATE INDEX idx_igctables_f4 ON igctables(tname);
CREATE INDEX idx_igctables_f5 ON igctables(mdate);
CREATE TABLE igctlog (  tid CHAR(17) NULL,  iuid CHAR(17) NULL,  userid VARCHAR(50) NULL,  content VARCHAR(255) NULL,  mdate BIGINT NULL,  pstatus INTEGER NULL);
CREATE INDEX idx_igctlog_f1 ON igctlog(tid);
CREATE INDEX idx_igctlog_f2 ON igctlog(iuid);
CREATE TABLE igctrashbin (  mts CHAR(17) NOT NULL,  iuid CHAR(17) NULL,  pid CHAR(17) NULL,  mctype INTEGER NULL,  cname VARCHAR(100) NULL,  mdate BIGINT NULL,  pstatus INTEGER NOT NULL,  node VARCHAR(1000),  description VARCHAR(1000),  memo VARCHAR(100) NULL,  sid CHAR(17),  mid CHAR(17),  objinfo VARCHAR(500) NULL,  revise INTEGER NOT NULL,  mrevise INTEGER NOT NULL,  trid CHAR(17) NULL,  qdes VARCHAR(100) NULL,  attrb1 VARCHAR(100) NULL,  attrb2 VARCHAR(100) NULL,  attrb3 VARCHAR(100) NULL,  attrb4 VARCHAR(100) NULL,  attrb5 VARCHAR(100) NULL,  is_sub INTEGER NOT NULL);
CREATE INDEX idx_igctrashbin_f1 ON igctrashbin(iuid);
CREATE INDEX idx_igctrashbin_f2 ON igctrashbin(pid, cname, mts, pstatus);
CREATE UNIQUE INDEX idx_igctrashbin_f3 ON igctrashbin(iuid, mts);
CREATE TABLE igcum (  iuid CHAR(17) NULL,  cip VARCHAR(40) NULL,  chost VARCHAR(255) NULL,  mdate BIGINT NULL,  userid VARCHAR(100) NULL,  flag CHAR(1) NULL,  cuid VARCHAR(100) NULL);
CREATE INDEX idx_igcum_f1 ON igcum(iuid);
CREATE TABLE igcuserduty (  mts CHAR(17) NOT NULL,  iuid CHAR(17) NULL,  sid CHAR(17) NULL);
CREATE INDEX idx_igcuserduty_f1 ON igcuserduty(iuid);
CREATE INDEX idx_igcuserduty_f2 ON igcuserduty(sid);
CREATE INDEX idx_igcuserduty_tenant ON igcuserduty(mts);
CREATE TABLE igcusers (  mts CHAR(17) NOT NULL,  iuid CHAR(17) NULL,  userid VARCHAR(100) NULL,  uname VARCHAR(100) NULL,  upasswd VARCHAR(100) NULL,  email VARCHAR(100) NULL,  active INTEGER NULL,  mdate BIGINT NULL,  gid CHAR(17) NOT NULL,  pid CHAR(17) NULL,  company VARCHAR(100) NULL,  position VARCHAR(1) NULL,  node VARCHAR(1000),  lacc INTEGER DEFAULT 0,  dfrm VARCHAR(50) NULL,  dtz VARCHAR(50) NULL,  a1 VARCHAR(50) NULL,  euser_id VARCHAR(20) NULL,  ssomod VARCHAR(20) NULL,  ssodsr VARCHAR(20) NULL,  description VARCHAR(1000) NULL);
CREATE INDEX idx_igcusers_f1 ON igcusers(iuid);
CREATE UNIQUE INDEX idx_igcusers_f2 ON igcusers(userid);
CREATE INDEX idx_igcusers_f3 ON igcusers(uname);
CREATE INDEX idx_igcusers_tenant ON igcusers(mts);
CREATE TABLE igclocale (  mts CHAR(17) NOT NULL,  iuid CHAR(17) NULL,  lid CHAR(17) NOT NULL,  mloc VARCHAR(5) NOT NULL,  lname VARCHAR(255) NOT NULL,  LDESC VARCHAR(255) NULL);
CREATE INDEX idx_igclocale_f1 ON igclocale(iuid);
CREATE INDEX idx_igclocale_f2 ON igclocale(lid);
CREATE INDEX idx_igclocale_f3 ON igclocale(lname);
CREATE INDEX idx_igclocale_tenant ON igclocale(mts);
CREATE TABLE igcdbhgrp (	seq INTEGER,	tname VARCHAR(100),	tdesc VARCHAR(100),	mstat INTEGER);
CREATE TABLE igcdbh (	seq INTEGER,	gid INTEGER,	tid VARCHAR(20),	drvcls VARCHAR(100),	drvname VARCHAR(100),	surl VARCHAR(100),	mstat INTEGER);
CREATE TABLE igcudb (	iuid CHAR(17),	mid CHAR(17),	tid VARCHAR(20),	tname VARCHAR(100),	drvcls VARCHAR(100),	drvname VARCHAR(30),	surl VARCHAR(100),	dbuid VARCHAR(40),	dbpwd VARCHAR(40),	mdate BIGINT,	cdate BIGINT);
CREATE UNIQUE INDEX p_igcudb_f1 ON igcudb (	iuid, mid, tname);
CREATE INDEX p_igcudb_f2 ON igcudb (mid);
CREATE TABLE igcudbauth (	sid CHAR(17),	mid CHAR(17),	writable CHAR(1),	c_manage CHAR(1));
CREATE TABLE igcsm (	iuid CHAR(17),	sid CHAR(17),	snder VARCHAR(255),	sndem VARCHAR(255),	email VARCHAR(255),	seq INTEGER,	subj VARCHAR(255),	cnts VARCHAR(255),	cdate BIGINT,	mdate BIGINT,	mstat CHAR(1),	reslcd VARCHAR(255),	msgtype VARCHAR(4));
CREATE INDEX idx_igcsm_f1 ON igcsm (iuid);
CREATE UNIQUE INDEX idx_igcsm_f2 ON igcsm (sid, seq);
CREATE TABLE igclc (	lc_type CHAR(5),	lc_name VARCHAR(100),	lc_desc VARCHAR(255));
CREATE UNIQUE INDEX idx_igclc_f1 ON igclc (lc_type, lc_name);
CREATE TABLE igcsc (  sid CHAR(17),  rid CHAR(17),  iuid CHAR(17),  mid CHAR(17),  mts_id CHAR(17),  scname VARCHAR(255) NULL,  sctype CHAR(2) NULL,  scoption VARCHAR(255) NULL,  crtdate CHAR(24) NULL,  uptdate CHAR(24) NULL,  pstatus CHAR(1) NULL,  a1 CHAR(1),  a1a VARCHAR(10),  a1b VARCHAR(100),  a1c VARCHAR(200));
CREATE TABLE igcscp (  mid CHAR(17),  sid CHAR(17),  seq INTEGER NOT NULL,  uptdate CHAR(14) NULL,  content VARCHAR(1000),  pstatus INTEGER NOT NULL);
CREATE INDEX idx_igcscp_01 ON igcscp(mid, sid, seq);
CREATE INDEX idx_igcscp_02 ON igcscp(uptdate);
CREATE TABLE igcsj (  jid CHAR(17),  sid CHAR(17),  crtdate CHAR(24) NULL,  upddate CHAR(24) NULL,  executeid VARCHAR(100) NULL,  message VARCHAR(255) NULL,  pstatus CHAR(1) NULL,  nexec_time BIGINT,  jobkeyname VARCHAR(100));
CREATE TABLE igcsjm (  jid CHAR(17),   executeid CHAR(17),   seq INTEGER NOT NULL,   content VARCHAR(1000),   uptdate CHAR(24) NULL,   pstatus INTEGER,   memo VARCHAR(100));
CREATE INDEX idx_igcsjm_01 ON igcsjm(jid, executeid, seq);
CREATE INDEX idx_igcsjm_02 ON igcsjm(uptdate);
CREATE TABLE igcctlduty (  iuid CHAR(17),  sid CHAR(17));
CREATE INDEX idx_igcctlduty_f1 ON igcctlduty (iuid);
CREATE TABLE igctk (  iuid CHAR(17),  suid CHAR(17),  memo VARCHAR(200) NULL,  createdate CHAR(24) NOT NULL,  expiredate CHAR(24) NULL,  updatedate CHAR(24) NULL,  auid CHAR(17) NULL,  pstatus CHAR(1) NULL,  mts CHAR(17) NULL);
CREATE UNIQUE INDEX idx_igctk_f1 ON igctk (iuid);
CREATE TABLE igcrptlogs (  mts CHAR(17) NOT NULL,  jobid CHAR(17),   userid VARCHAR(50),   hostaddr VARCHAR(100),   hostname VARCHAR(100),   objpath VARCHAR(200),  objname VARCHAR(200),   iuid CHAR(17),   luid CHAR(17),   pstatus INTEGER,   crttime CHAR(24) NOT NULL,   updtime CHAR(24) NOT NULL,   lmsg VARCHAR(200),  plast INTEGER,  pellapsed BIGINT);
CREATE INDEX idx_igcrptlogs_f1 ON igcrptlogs (jobid, pstatus, mts);
CREATE INDEX idx_igcrptlogs_f2 ON igcrptlogs (userid);
CREATE INDEX idx_igcrptlogs_f3 ON igcrptlogs (crttime, updtime);
CREATE INDEX idx_igcrptlogs_tenant ON igcrptlogs(mts);
CREATE TABLE igcaccl (	tuid CHAR(17) NOT NULL, 	cuid CHAR(17) NOT NULL, 	mtsid CHAR(17), 	cdate BIGINT, 	mdate BIGINT, 	lstat CHAR(1), 	ltemp CHAR(1), 	userid VARCHAR(100), 	mts_name VARCHAR(100), 	lhost VARCHAR(100), 	lhostip VARCHAR(100),	lloc VARCHAR(10));
CREATE INDEX idx_igcaccl_01 ON igcaccl (tuid, cuid);
CREATE TABLE igcaccls (	tuid CHAR(17) NOT NULL, 	suid CHAR(17) NOT NULL, 	mdate BIGINT, 	lstat CHAR(1),	lloc VARCHAR(10));
CREATE INDEX idx_igcaccls_01 ON igcaccls (tuid, suid);
CREATE TABLE igcfseq (	mts CHAR(17),	sname VARCHAR(20),	sseq INTEGER);
CREATE UNIQUE INDEX idx_igcfseq_01 ON igcfseq(mts, sname);
CREATE TABLE igchdo (	sid CHAR(17),	mid CHAR(17),	lid CHAR(17),	jobtype VARCHAR(50),	pstatus INTEGER,	cdate BIGINT,	mdate BIGINT);
CREATE TABLE igchdoc (	lid CHAR(17),	seq INTEGER NOT NULL,	content VARCHAR(1000) NOT NULL);
CREATE TABLE igchds (	iuid CHAR(17),	rid CHAR(17),	pstatus INTEGER,	cdate BIGINT NOT NULL,	mdate BIGINT NOT NULL);
CREATE TABLE igccache (	fid CHAR(17) NOT NULL,	sid CHAR(17) NOT NULL,	duid CHAR(17) NOT NULL,	mts CHAR(17) NOT NULL,	checksum VARCHAR(255),	pstatus INTEGER,	udate BIGINT);
CREATE INDEX idx_igccache_01 ON igccache (checksum);
CREATE INDEX idx_igccache_02 ON igccache (mts, sid);
CREATE TABLE igcfunc (	fid INTEGER NOT NULL,	name VARCHAR(100) NOT NULL,	dbtype INTEGER NOT NULL,	description VARCHAR(255) NULL,	fvalue VARCHAR(255) NOT NULL,	is_builtin CHAR(1) NOT NULL,	func_type INTEGER NOT NULL,	pstatus INTEGER NOT NULL,	cdate BIGINT NOT NULL,	udate BIGINT NOT NULL,	fcid INTEGER NOT NULL);
CREATE UNIQUE INDEX idx_igcfunc_01 ON igcfunc (fid);
CREATE UNIQUE INDEX idx_igcfunc_02 ON igcfunc (name, dbtype);
CREATE UNIQUE INDEX idx_igcfunc_03 ON igcfunc (name, dbtype, pstatus);
CREATE TABLE igcfunc_c (	fcid CHAR(17) NOT NULL,	name VARCHAR(100) NOT NULL,	description VARCHAR(255) NULL,	is_custom CHAR(1) NOT NULL,	pstatus INTEGER NOT NULL,	cdate BIGINT NOT NULL,	udate BIGINT NOT NULL);
CREATE UNIQUE INDEX idx_igcfunc_c01 ON igcfunc_c (fcid);
CREATE UNIQUE INDEX idx_igcfunc_c02 ON igcfunc_c (name);
CREATE TABLE igctablejoin (	rel_id CHAR(17) NOT NULL, 	model_id CHAR(17) NOT NULL, 	table_id CHAR(17) NOT NULL, 	join_key INTEGER NOT NULL, 	udate BIGINT NOT NULL);
CREATE UNIQUE INDEX idx_igctbjoin_c01 ON igctablejoin (rel_id);
CREATE INDEX idx_igctbjoin_c02 ON igctablejoin (model_id);
CREATE INDEX idx_igctbjoin_c03 ON igctablejoin (model_id, table_id);
CREATE TABLE igcjoins (	join_id CHAR(17) NOT NULL,	fr_model CHAR(17) NOT NULL, 	fr_table CHAR(17) NOT NULL, 	fr_field CHAR(17) NOT NULL,	to_model CHAR(17) NOT NULL, 	to_table CHAR(17) NOT NULL, 	to_field CHAR(17) NOT NULL,	cardinal VARCHAR(50) NOT NULL,	s_formula VARCHAR(255) NULL,	t_formula VARCHAR(255) NULL,	udate BIGINT NOT NULL);
CREATE UNIQUE INDEX idx_igcjoins_c01 ON igcjoins (join_id);
CREATE INDEX idx_igcjoins_c02 ON igcjoins (fr_model, fr_table, fr_field);
CREATE INDEX idx_igcjoins_c03 ON igcjoins (to_model, to_table, to_field);
CREATE TABLE igcsubscript (	scid CHAR(17) NOT NULL, 	iuid CHAR(17) NOT NULL, 	pid CHAR(17) NOT NULL,	mctype INTEGER NULL,	from_mts CHAR(17) NOT NULL,	to_mts CHAR(17) NOT NULL,	mdate BIGINT NULL,	cdate BIGINT NULL);
CREATE UNIQUE INDEX idx_subscript_01 ON igcsubscript(scid);
CREATE UNIQUE INDEX idx_subscript_02 ON igcsubscript(iuid, from_mts, to_mts);
CREATE INDEX idx_subscript_03 ON igcsubscript(mctype);
CREATE TABLE igcdbareq (	reqid CHAR(17) NOT NULL,	muid CHAR(17) NOT NULL,	fuid CHAR(17) NOT NULL,	sid CHAR(17) NOT NULL,	pstatus INTEGER NOT NULL,	description VARCHAR(200) NULL,	mts CHAR(17) NOT NULL,	mdate BIGINT NULL,	cdate BIGINT NULL);
CREATE UNIQUE INDEX idx_dbareq_01 ON igcdbareq(reqid);
CREATE UNIQUE INDEX idx_dbareq_02 ON igcdbareq(fuid, sid);
CREATE TABLE igcsso (	mtu CHAR(17) NOT NULL,	muid CHAR(17) NOT NULL,	ssomod VARCHAR(20) NOT NULL,	fname VARCHAR(200) NOT NULL,	seq INTEGER NOT NULL,	svalue VARCHAR(255) NOT NULL,	mdate BIGINT NOT NULL,  	cdate BIGINT NOT NULL);
CREATE UNIQUE INDEX idx_sso_01 ON igcsso(mtu, muid, ssomod, fname, seq);
CREATE TABLE igcshare (	suid CHAR(17) NOT NULL,	mtu CHAR(17) NOT NULL,	muid CHAR(17) NOT NULL,	p_status CHAR(1) NOT NULL,	b_public CHAR(1) NOT NULL,	p_url VARCHAR(255) NOT NULL,	acc_count INTEGER NOT NULL,	cdate BIGINT NOT NULL,	mdate BIGINT NOT NULL,	ldate BIGINT NOT NULL);
CREATE UNIQUE INDEX idx_share_01 ON igcshare(suid);
CREATE INDEX idx_share_02 ON igcshare(suid, mtu, muid);
CREATE TABLE igccudlog (suid CHAR(17) NOT NULL, nickname VARCHAR(255) NOT NULL, p_status INTEGER NOT NULL, cdate BIGINT NOT NULL,mdate BIGINT NOT NULL);
CREATE UNIQUE INDEX idx_cudlog_01 ON igccudlog(suid);
CREATE TABLE igccuddata (suid CHAR(17) NOT NULL, seq INTEGER NOT NULL, cdate BIGINT NOT NULL, s_intent VARCHAR(255) NOT NULL, s_utter VARCHAR(255) NOT NULL, s_resp VARCHAR(255) NOT NULL);
CREATE UNIQUE INDEX idx_cuddata_01 ON igccuddata(suid, seq);
INSERT INTO igcmts (mtu, mtname, mdate, pstatus, a1, a2) VALUES ('0122483f-0155fb46','ROOT',1407568418000,'A',NULL,NULL);
INSERT INTO igcdepts (mts, gid, dname, active, mdate, pid, node, mid, description, dtype, privilege, lacc, cacc, dept_id) VALUES ('0122483f-0155fb46','0122483f-0155fb46','AdminGroup',1,1260464461000,'0125a045-017ae681','NODE@0125A045-017AE681@0122483F-0155FB46',NULL,'lll','A',NULL,0,0,NULL);
INSERT INTO igcdepts (mts, gid, dname, active, mdate, pid, node, mid, description, dtype, privilege, lacc, cacc, dept_id) VALUES ('0122483f-0155fb46','0125a045-017ae681','RootGroup',1,1261069261000,NULL,'NODE@0125A045-017AE681','0125a5a3-0145447c',NULL,'A',NULL,0,0,NULL);
INSERT INTO igcduty (mts, sid, dname, pstatus, dutytype, mdate, description, node) VALUES ('0122483f-0155fb46','4fce8d2e-6d5144d0','Admins',1,'A',NULL,'lll','');
INSERT INTO igcduty (mts, sid, dname, pstatus, dutytype, mdate, description, node) VALUES ('0122483f-0155fb46','0122483f-0155fb4d','EveryOne',1,'A',NULL,NULL,'');
INSERT INTO igcduty (mts, sid, dname, pstatus, dutytype, mdate, description, node) VALUES ('0122483f-0155fb46','0125a1a8-01d413a0','LocalAdmin',1,'A',NULL,NULL,'');
INSERT INTO igcstatus (pstatus, description, STYPE) VALUES (1,'Active',1);
INSERT INTO igcstatus (pstatus, description, STYPE) VALUES (2,'Deleted',1);
INSERT INTO igcstatus (pstatus, description, STYPE) VALUES (1,'Locked',2);
INSERT INTO igcstatus (pstatus, description, STYPE) VALUES (2,'UnLocked',2);
INSERT INTO igcstatus (pstatus, description, STYPE) VALUES (3,'ForcedUnLocked',2);
INSERT INTO igcstatus (pstatus, description, STYPE) VALUES (4,'LogoutUnLock',2);
INSERT INTO igcstatus (pstatus, description, STYPE) VALUES (5,'CloseUnLock',2);
INSERT INTO igcusers (mts, iuid, userid, uname, upasswd, email, active, mdate, gid, pid, company, position, node, lacc, dfrm, dtz, a1, euser_id) VALUES ('0122483f-0155fb46','54c1cce7-d7734fac','admin','Admin','D033E22AE348AEB5660FC2140AEC35850C4DA997','admin@company.com',1,1407568418000,'0122483f-0155fb46','01259d66-01915308',NULL,NULL,'NODE@0125A045-017AE681@0122483F-0155FB46@0122483f-0155fb46',0,NULL,NULL,NULL,NULL);
INSERT INTO igcuserduty (mts, iuid, sid) VALUES ('0122483f-0155fb46','54c1cce7-d7734fac','4fce8d2e-6d5144d0');
INSERT INTO igcuserduty (mts, iuid, sid) VALUES ('0122483f-0155fb46','54c1cce7-d7734fac','0122483f-0155fb4d');
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (103,'!=',0,null,'${P1} != ${P2}','T',1,1,0,0,4000);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (84,'<',0,null,'${P1} < ${P2}','T',1,1,0,0,4000);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (85,'<=',0,null,'${P1} <= ${P2}','T',1,1,0,0,4000);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (82,'<>',0,null,'${P1} <> ${P2}','T',1,1,0,0,4000);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (81,'=',0,null,'${P1} = ${P2}','T',1,1,0,0,4000);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (83,'>',0,null,'${P1} > ${P2}','T',1,1,0,0,4000);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (86,'>=',0,null,'${P1} >= ${P2}','T',1,1,0,0,4000);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (92,'BETWEEN',0,null,'BETWEEN ${P1} AND ${P2}','T',1,1,0,0,4000);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (116,'EXISTS',0,null,'EXISTS (${P1})','T',1,1,0,0,4000);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (88,'IN',0,null,'IN (${P1})','T',1,1,0,0,4000);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (90,'IS NOT NULL',0,null,'IS NOT NULL','T',1,1,0,0,4000);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (89,'IS NULL',0,null,'IS NULL','T',1,1,0,0,4000);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (87,'LIKE',0,null,'LIKE ${P1}','T',1,1,0,0,4000);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (93,'NOT BETWEEN',0,null,'NOT BETWEEN ${P1} AND ${P2}','T',1,1,0,0,4000);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (91,'NOT IN',0,null,'NOT IN (${P1})','T',1,1,0,0,4000);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (100,'NOT LIKE',0,null,'NOT LIKE ${P1}','T',1,1,0,0,4000);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (247,'ASCIISTR',0,null,'ASCIISTR','T',6,1,0,0,4002);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (50,'CHARTOROWID',0,null,'CHARTOROWID','T',6,1,0,0,4002);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (248,'COMPOSE',0,null,'COMPOSE','T',6,1,0,0,4002);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (51,'CONVERT',0,null,'CONVERT','T',6,1,0,0,4002);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (252,'DECOMPOSE',0,null,'DECOMPOSE','T',6,1,0,0,4002);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (52,'HEXTORAW',0,null,'HEXTORAW','T',6,1,0,0,4002);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (156,'NUMTODSINTERVAL',0,null,'NUMTODSINTERVAL','T',13,1,0,0,4002);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (157,'NUMTOYMINTERVAL',0,null,'NUMTOYMINTERVAL','T',13,1,0,0,4002);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (53,'RAWTOHEX',0,null,'RAWTOHEX','T',6,1,0,0,4002);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (54,'ROWIDTOCHAR',0,null,'ROWIDTOCHAR','T',6,1,0,0,4002);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (55,'TO_CHAR',0,null,'TO_CHAR','T',6,1,0,0,4002);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (58,'TO_DATE',0,null,'TO_DATE','T',6,1,0,0,4002);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (59,'TO_LABEL',0,null,'TO_LABEL','T',6,1,0,0,4002);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (60,'TO_MULTI_BYTE',0,null,'TO_MULTI_BYTE','T',6,1,0,0,4002);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (61,'TO_NUMBER',0,null,'TO_NUMBER','T',6,1,0,0,4002);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (62,'TO_SINGLE_BYTE',0,null,'TO_SINGLE_BYTE','T',6,1,0,0,4002);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (255,'UNISTR',0,null,'UNISTR','T',6,1,0,0,4002);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (42,'ADD_MONTHS',0,null,'ADD_MONTHS','T',9,1,0,0,4006);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (250,'CURRENT_DATE',0,null,'CURRENT_DATE','T',9,1,0,0,4006);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (251,'DBTIMEZONE',0,null,'DBTIMEZONE','T',9,1,0,0,4006);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (105,'EUL_DATE_TRUNC',0,null,'EUL_DATE_TRUNC','T',9,1,0,0,4006);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (43,'LAST_DAY',0,null,'LAST_DAY','T',9,1,0,0,4006);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (44,'MONTHS_BETWEEN',0,null,'MONTHS_BETWEEN','T',9,1,0,0,4006);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (45,'NEW_TIME',0,null,'NEW_TIME','T',9,1,0,0,4006);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (46,'NEXT_DAY',0,null,'NEXT_DAY','T',9,1,0,0,4006);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (47,'ROUND2',0,null,'ROUND','T',9,1,0,0,4006);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (254,'SESSIONTIMEZONE',0,null,'SESSIONTIMEZONE','T',9,1,0,0,4006);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (48,'SYSDATE',0,null,'SYSDATE','T',9,1,0,0,4006);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (119,'TIMESTAMPADD',0,null,'TIMESTAMPADD','T',9,1,0,0,4006);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (120,'TIMESTAMPDIFF',0,null,'TIMESTAMPDIFF','T',9,1,0,0,4006);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (49,'TRUNC2',0,null,'TRUNC','T',9,1,0,0,4006);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (104,'AVG',0,null,'AVG','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (109,'AVG_DISTINCT',0,null,'AVG(DISTINCT','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (164,'CORR',0,null,'CORR','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (73,'COUNT',0,null,'COUNT','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (110,'COUNT_DISTINCT',0,null,'COUNT(DISTINCT','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (165,'COVAR_POP',0,null,'COVAR_POP','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (166,'COVAR_SAMP',0,null,'COVAR_SAMP','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (228,'CUME_DIST1',0,null,'CUME_DIST','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (74,'GLB',0,null,'GLB','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (75,'LUB',0,null,'LUB','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (76,'MAX',0,null,'MAX','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (111,'MAX_DISTINCT',0,null,'MAX(DISTINCT','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (77,'MIN',0,null,'MIN','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (112,'MIN_DISTINCT',0,null,'MIN_DISTINCT','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (221,'PERCENTILE_CONT1',0,null,'PERCENTILE_CONT','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (223,'PERCENTILE_DISC1',0,null,'PERCENTILE_DISC','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (227,'PERCENT_RANK1',0,null,'PERCENT_RANK','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (171,'REGR_AVGX',0,null,'REGR_AVGX','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (172,'REGR_AVGY',0,null,'REGR_AVGY','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (169,'REGR_COUNT',0,null,'REGR_COUNT','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (168,'REGR_INTERCEPT',0,null,'REGR_INTERCEPT','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (170,'REGR_R2',0,null,'REGR_R2','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (167,'REGR_SLOPE',0,null,'REGR_SLOPE','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (173,'REGR_SXX',0,null,'REGR_SXX','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (175,'REGR_SXY',0,null,'REGR_SXY','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (174,'REGR_SYY',0,null,'REGR_SYY','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (107,'ROWCOUNT',0,null,'ROWCOUNT','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (78,'STDDEV',0,null,'STDDEV','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (113,'STDDEV_DISTINCT',0,null,'STDDEV(DISTINCT','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (176,'STDDEV_POP',0,null,'STDDEV_POP','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (177,'STDDEV_SAMP',0,null,'STDDEV_SAMP','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (1,'SUM',0,null,'SUM','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (114,'SUM_DISTINCT',0,null,'SUM(DISTINCT','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (106,'SUM_SQUARES',0,null,'SUM_SQUARES','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (80,'VARIANCE',0,null,'VARIANCE','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (115,'VARIANCE_DISTINCT',0,null,'VARIANCE(DISTINCT','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (178,'VAR_POP',0,null,'VAR_POP','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (179,'VAR_SAMP',0,null,'VAR_SAMP','T',4,1,0,0,4008);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (98,'AND',0,null,'___ AND ___','T',3,1,0,0,4010);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (101,'NOT',0,null,'NOT ${P1}','T',3,1,0,0,4010);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (99,'OR',0,null,'___ OR ___','T',3,1,0,0,4010);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (96,'*',0,null,'*','T',2,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (94,'+',0,null,'(___ + ___)','T',2,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (95,'-1',0,null,'-','T',2,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (97,'/',0,null,'(___ / ___)','T',2,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (79,'ABS',0,null,'ABS(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (159,'ACOS',0,null,'ACOS(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (162,'ASIN',0,null,'ASIN(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (160,'ATAN',0,null,'ATAN(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (161,'ATAN2',0,null,'ATAN2(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (2,'CEIL',0,null,'CEIL(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (3,'COS',0,null,'COS(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (4,'COSH',0,null,'COSH(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (5,'EXP',0,null,'EXP(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (6,'FLOOR',0,null,'FLOOR(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (7,'LN',0,null,'LN(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (8,'LOG',0,null,'LOG(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (9,'MOD',0,null,'MOD(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (10,'POWER',0,null,'POWER(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (11,'ROUND1',0,null,'ROUND(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (12,'SIGN',0,null,'SIGN(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (13,'SIN',0,null,'SIN(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (14,'SINH',0,null,'SINH(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (15,'SQRT',0,null,'SQRT(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (16,'TAN',0,null,'TAN(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (17,'TANH',0,null,'TANH(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (18,'TRUNC1',0,null,'TRUNC(${PS})','T',10,1,0,0,4012);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (118,'ALL',0,null,'ALL','T',1,1,0,0,4014);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (117,'ANY',0,null,'ANY','T',1,1,0,0,4014);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (153,'CASE',0,null,'CASE','T',7,1,0,0,4014);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (249,'COALESCE',0,null,'COALESCE','T',7,1,0,0,4014);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (102,'DECODE',0,null,'DECODE','T',7,1,0,0,4014);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (63,'DUMP',0,null,'DUMP','T',7,1,0,0,4014);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (155,'ELSE',0,null,'ELSE','T',7,1,0,0,4014);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (64,'GREATEST',0,null,'GREATEST','T',7,1,0,0,4014);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (65,'GREATEST_LB',0,null,'GREATEST_LB','T',7,1,0,0,4014);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (66,'LEAST',0,null,'LEAST','T',7,1,0,0,4014);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (67,'LEAST_UB',0,null,'LEAST_UB','T',7,1,0,0,4014);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (253,'NULLIF',0,null,'NULLIF','T',7,1,0,0,4014);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (68,'NVL',0,null,'NVL','T',7,1,0,0,4014);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (108,'ROWNUM',0,null,'ROWNUM','T',7,1,0,0,4014);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (69,'UID',0,null,'UID','T',7,1,0,0,4014);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (70,'USER',0,null,'USER','T',7,1,0,0,4014);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (71,'USERENV',0,null,'USERENV','T',7,1,0,0,4014);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (72,'VSIZE',0,null,'VSIZE','T',7,1,0,0,4014);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (154,'WHEN',0,null,'WHEN','T',7,1,0,0,4014);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (36,'ASCII',0,null,'ASCII','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (19,'CHR',0,null,'CHR','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (20,'CONCAT',0,null,'CONCAT','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (21,'INITCAP',0,null,'INITCAP','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (37,'INSTR',0,null,'INSTR','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (38,'INSTRB',0,null,'INSTRB','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (39,'LENGTH',0,null,'LENGTH','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (40,'LENGTHB',0,null,'LENGTHB','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (22,'LOWER',0,null,'LOWER','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (23,'LPAD',0,null,'LPAD','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (24,'LTRIM',0,null,'LTRIM','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (41,'NLSSORT',0,null,'NLSSORT','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (25,'NLS_INITCAP',0,null,'NLS_INITCAP','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (26,'NLS_LOWER',0,null,'NLS_LOWER','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (27,'NLS_UPPER',0,null,'NLS_UPPER','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (28,'REPLACE',0,null,'REPLACE','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (29,'RPAD',0,null,'RPAD','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (30,'RTRIM',0,null,'RTRIM','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (31,'SOUNDEX',0,null,'SOUNDEX','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (32,'SUBSTR',0,null,'SUBSTR','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (33,'SUBSTRB',0,null,'SUBSTRB','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (34,'TRANSLATE',0,null,'TRANSLATE','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (35,'UPPER',0,null,'UPPER','T',5,1,0,0,4016);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (132,'ASC',0,null,'ASC','T',14,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (198,'CORR1',0,null,'CORR','T',4,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (199,'COVAR_POP1',0,null,'COVAR_POP','T',4,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (200,'COVAR_SAMP1',0,null,'COVAR_SAMP','T',4,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (246,'CUBE',0,null,'CUBE','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (124,'CUME_DIST',0,null,'CUME_DIST','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (143,'CURRENTROW',0,null,'CURRENTROW','T',14,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (149,'DAY',0,null,'DAY','T',14,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (218,'DENSERANKFIRST',0,null,'DENSERANKFIRST','T',14,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (219,'DENSERANKLAST',0,null,'DENSERANKLAST','T',14,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (122,'DENSE_RANK',0,null,'DENSE_RANK','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (133,'DESC',0,null,'DESC','T',14,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (180,'FIRST_VALUE',0,null,'FIRST_VALUE','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (145,'FOLLOWING',0,null,'FOLLOWING','T',14,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (258,'GROUPING',0,null,'GROUPING','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (244,'GROUPINGSETS',0,null,'GROUPINGSETS','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (256,'GROUPING_ID',0,null,'GROUPING_ID','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (257,'GROUP_ID',0,null,'GROUP_ID','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (150,'HOUR',0,null,'HOUR','T',14,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (146,'INTERVAL',0,null,'INTERVAL','T',14,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (158,'INTERVALPRECISION',0,null,'INTERVALPRECISION','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (216,'KEEP',0,null,'KEEP','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (217,'KEEPCOMPONENT',0,null,'KEEPCOMPONENT','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (126,'LAG',0,null,'LAG','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (181,'LAST_VALUE',0,null,'LAST_VALUE','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (127,'LEAD',0,null,'LEAD','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (151,'MINUTE',0,null,'MINUTE','T',14,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (148,'MONTH',0,null,'MONTH','T',14,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (139,'NPASSBETWEEN',0,null,'NPASSBETWEEN','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (140,'NPASSBETWEENCOMP',0,null,'NPASSBETWEENCOMP','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (131,'NPASSORDERCOMP',0,null,'NPASSORDERCOMP','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (125,'NTILE',0,null,'NTILE','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (134,'NULLSFIRST',0,null,'NULLSFIRST','T',14,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (135,'NULLSLAST',0,null,'NULLSLAST','T',14,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (130,'ORDER',0,null,'ORDER','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (128,'OVER',0,null,'OVER','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (129,'PARTITION',0,null,'PARTITION','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (220,'PERCENTILE_CONT',0,null,'PERCENTILE_CONT','T',4,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (222,'PERCENTILE_DISC',0,null,'PERCENTILE_DISC','T',4,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (123,'PERCENT_RANK',0,null,'PERCENT_RANK','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (144,'PRECEDING',0,null,'PRECEDING','T',14,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (138,'RANGE',0,null,'RANGE','T',14,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (121,'RANK',0,null,'RANK','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (182,'RATIO_TO_REPORT',0,null,'RATIO_TO_REPORT','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (245,'ROLLUP',0,null,'ROLLUP','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (137,'ROWS',0,null,'ROWS','T',14,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (183,'ROW_NUMBER',0,null,'ROW_NUMBER','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (152,'SECOND',0,null,'SECOND','T',14,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (142,'UNBOUNDEDFOLLOWING',0,null,'UNBOUNDEDFOLLOWING','T',14,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (141,'UNBOUNDEDPRECEDING',0,null,'UNBOUNDEDPRECEDING','T',14,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (224,'WIDTH_BUCKET',0,null,'WIDTH_BUCKET','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (136,'WINDOW',0,null,'WINDOW','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (214,'WITHINGROUP',0,null,'WITHINGROUP','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (215,'WITHINGROUPCOMPONENT',0,null,'WITHINGROUPCOMPONENT','T',13,1,0,0,4018);
insert into igcfunc (fid, name, dbtype, description, fvalue, is_builtin, func_type, pstatus, cdate, udate, fcid) values (147,'YEAR',0,null,'YEAR','T',14,1,0,0,4018);
INSERT INTO igcdbhgrp (seq, tname, tdesc, mstat) VALUES (1, 'Relational JDBC Connector', '', 1);
INSERT INTO igcdbhgrp (seq, tname, tdesc, mstat) VALUES (2, 'Cloud Connector', '', 1);
INSERT INTO igcdbhgrp (seq, tname, tdesc, mstat) VALUES (3, 'ERP BI Connector', '', 1);
INSERT INTO igcdbhgrp (seq, tname, tdesc, mstat) VALUES (4, 'Embedded Datasource', '', 1);
INSERT INTO igcdbhgrp (seq, tname, tdesc, mstat) VALUES (5, 'Bigdata Connector', '', 1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (1, 1, 'oracle','oracle.jdbc.OracleDriver','Oracle Thin Driver','jdbc:oracle:thin:@<server>[:<1521>]:<service_name>',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (2, 1, 'mysql','com.mysql.jdbc.Driver','MySQL Driver','jdbc:mysql://<hostname>[,<failoverhost>][:<3306>]/<dbname>[?<param1>=<value1>][&<param2>=<value2>]',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (3, 1, 'db2','com.ibm.as400.access.AS400JDBCDriver','IBM DB2 Driver','jdbc:db2:<dbname>',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (4, 1, 'as400','com.ibm.as400.access.AS400JDBCDriver','IBM AS400 DB2 Driver','jdbc:as400:<dbname>',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (5, 1, 'mssql','com.microsoft.sqlserver.jdbc.SQLServerDriver','Microsoft MSSQL Server JDBC Driver','jdbc:microsoft:sqlserver://<server_name>:<1433>;databaseName=<dbname>;integratedSecurity=true;',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (6, 1, 'postg','org.postgresql.Driver','PostgreSQL','jdbc:postgresql:[<//host>[:<5432>/]]<database>',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (7, 1, 'sybase_iq','com.sybase.jdbc4.jdbc.SybDriver','Sybase IQ','jdbc:sybase:Tds:@<server>[:<7100>/]?ServiceName=<dbname>',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (8, 1, 'sybase_ase','com.sybase.jdbc4.jdbc.SybDriver','Sybase ASE','jdbc:sybase:Tds:@<server>[:<7100>/]/<dbname>?ENABLE_SSL=true&SSL_TRUST_ALL_CERTS=true',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (9, 1, 'exasol','com.exasol.jdbc.EXADriver','Exasol InMemory Database','jdbc:exa:<HOST>:<PORT>;schema=<DB>',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (10, 2, 'sforce','sforce','Salesforce connection','sforce',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (11, 3, 'ebs','com.amplix.connector.ebs.OracleEBSJdbcDriver','Oracle EBS application','jdbc:oracleebs:@<server>[:<1521>]:<service_name>',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (12, 2, 'ldap','ldap','LDAP data source','ldap',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (13, 3, 'sapbw','sapbw','SAP BW Data','sapbw',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (14, 3, 'essbase','essbase','Oralce Hyperion Essbase','essbase',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (15, 1, 'jdbcodbc','sun.jdbc.odbc.JdbcOdbcDriver','JDBC ODBC Bridge','jdbc:odbc:<alias>',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (16, 5, 'hive','org.apache.hadoop.hive.jdbc.HiveDriver','Hive2','jdbc:hive://<server>:<10000>/default',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (17, 5, 'mongodb','-','MongoDB NoSQL Database','-',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (18, 4, 'apacheembd','org.apache.derby.jdbc.EmbeddedDriver','Apache Derby Embedded','jdbc:derby:<database>[;create=true]',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (19, 4, 'h2','org.h2.Driver','H2 Database','jdbc:h2:file:~/<location>',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (20, 3, 'jde','com.amplix.connector.jde.OracleJDEJdbcDriver','Oracle JD Edwards ERP','jdbc:oraclejde:@<server>[:<1521>]:<service_name>',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (21, 2, 'amplix','com.amplix.connector.metadb.MetaDBJdbcDriver','amplix meta readonly','jdbc:amplix:@:service_name',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (22, 2, 'soap','soap','SOAP WebService','soap',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (23, 2, 'rest','rest','REST WebService','rest',1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (24, 5, 'elasticsearch', '-', 'ElasticSearch', '-', 1);
INSERT INTO igcdbh (seq, gid, tid, drvcls, drvname, surl, mstat) VALUES (29, 2, 'pardot','pardot','Pardot connection','pardot',1);
DELETE FROM igcserver;
INSERT INTO igcserver (pname, content, mdate) VALUES ('VERSION', '4.0', 1574914423042);
INSERT INTO igcserver (pname, content, mdate) VALUES ('ProductVersion', '4.13', 1574914423042);


UPDATE igcusers SET upasswd='46E3D772A1888EADFF26C7ADA47FD7502D796E07' WHERE userid='admin';
