/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2019-06-19 03:25:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    request.setCharacterEncoding("utf-8");
    java.text.SimpleDateFormat formatter = new java.text.SimpleDateFormat("yyyyMMddHHmmss");
    String _d = formatter.format(new java.util.Date());
    
    String uri = request.getServerName();
    String mts = null;
    
    if (uri != null && uri.equals("") == false)
    {
        mts = com.amplix.rpc.igcRpc.LoadMTS(uri);
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>amplix</title>\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"chrome=IE8\">\r\n");
      out.write("    <meta http-equiv=\"Cache-Control\" content=\"no-cache, no-store, must-revalidate\">\r\n");
      out.write("\t<meta http-equiv=\"Pragma\" content=\"no-cache\">\r\n");
      out.write("\t<meta http-equiv=\"Expires\" content=\"0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./main/css/main.min.css?_dc=201906111958\" />\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./main/css/mainpage_ie.css\" />\r\n");
      out.write("<![endif]-->\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"favicon.ico\" type=\"image/x-icon\" />\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./main/js/jquery-1.12.0.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    var __mts_id = null;\r\n");
      out.write("   \t</script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./main/js/main.min.js?_dc=201906111958\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"index nav-light hoverable\">\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"header\" class=\"header\" role=\"banner\">\r\n");
      out.write("\t   <div class=\"header-item with-site-logo\">\r\n");
      out.write("\t      <a class=\"site-logo site-logo-link\" href=\"./\">\r\n");
      out.write("\t         <div class=\"site-logo-image\">\r\n");
      out.write("\t            amplix\r\n");
      out.write("\t         </div>\r\n");
      out.write("\t      </a>\r\n");
      out.write("\t   </div>\r\n");
      out.write("\t   <div class=\"nav nav-site\" data-nav-name=\"mobile\">\r\n");
      out.write("\t      <ul>\r\n");
      out.write("\t         <li>\r\n");
      out.write("\t            <a class=\"meet\" href=\"http://www.amplixbi.com/\">Who we are</a>\r\n");
      out.write("\t         </li>\r\n");
      out.write("\t         <li class=\"mobile-is-hidden device-is-hidden\">\r\n");
      out.write("\t            <a class=\"download\" href=\"http://www.amplixbi.com/en/download.jsp\">Download</a>\r\n");
      out.write("\t         </li>\r\n");
      out.write("\t         <li class=\"last-default\">\r\n");
      out.write("\t            <a class=\"help\" href=\"http://www.amplixbi.com/en/manual/\">Help</a>\r\n");
      out.write("\t         </li>\r\n");
      out.write("\t         <li class=\"mobile-is-hidden float-in\">\r\n");
      out.write("\t            <a id=\"btn_maintop\" class=\"go-to-drive get-started\" href=\"\">Go to Top</a>\r\n");
      out.write("\t         </li>\r\n");
      out.write("\t      </ul>\r\n");
      out.write("\t   </div>\r\n");
      out.write("\t   <div class=\"mobile-nav-toggle js-mobilenav\">\r\n");
      out.write("\t      <div class=\"icon toggle-nav-open js-mobilenav-toggle icon-mobile-open\" data-target-nav=\"mobile\"></div>\r\n");
      out.write("\t      <div class=\"icon icon-mobile-close toggle-nav-closed js-mobilenav-toggle-close\" data-target-nav=\"mobile\"></div>\r\n");
      out.write("\t   </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"section section-intro section-panel-fullscreen js-fullscreen\" style=\"opacity: 1;\">\r\n");
      out.write("\t   <div class=\"section-photo-fullscreen section-photo js-parallax-image js-responsive-image loaded\" data-breakpoints=\"320,768,1024,1200,1600\" data-known-dimensions=\"false\" data-origin=\"0\" data-preserve-aspect-ratio=\"false\" data-reverse-parallax=\"true\" data-src=\"./main/images/home/intro.jpg\" style=\"height: 872px; background-image: url(./main/images/main_bg.png);\"></div>\r\n");
      out.write("\t   <div class=\"section-centered section-vertical-align js-vertical-align js-parallax-image\" data-origin=\"0\" data-parallax-fade=\"true\" data-parallax-speed=\"3\" data-reverse-parallax=\"true\" style=\"opacity: 1;\">\r\n");
      out.write("\t      <div class=\"one-whole\">\r\n");
      out.write("\t         <h1 class=\"section-headline section-headline-large section-headline-white\">\r\n");
      out.write("\t            Scientific Analytics, ready for you\r\n");
      out.write("\t         </h1>\r\n");
      out.write("\t         <a class=\"maia-button button-download mobile-is-hidden get-started\" href=\"#start\">Go to Demo</a>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t   </div>\r\n");
      out.write("\t   <div class=\"arrow-hint\">\r\n");
      out.write("\t      <a class=\"gweb-smoothscroll-control\" href=\"#start\">\r\n");
      out.write("\t         <div class=\"icon icon-arrow-hint animated-arrow-1\"></div>\r\n");
      out.write("\t         <div class=\"icon icon-arrow-hint animated-arrow-2\"></div>\r\n");
      out.write("\t      </a>\r\n");
      out.write("\t   </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"unfixed-wrapper\" id=\"start\" style=\"opacity: 1;\">\r\n");
      out.write("\t   <div id=\"nav-tick\" style=\"top: -68px;\"></div>\r\n");
      out.write("\t   <div class=\"section section-filetypes js-hinted-fullscreen\" style=\"height: 303px\">\r\n");
      out.write("\t      <div class=\"content\">\r\n");
      out.write("\t      \t\r\n");
      out.write("\t         <div class=\"column column-left with-example\">\r\n");
      out.write("\t         \t<div class=\"category-panels-container\">\r\n");
      out.write("\t\t\t\t    <div class=\"category-panel\">\r\n");
      out.write("\t\t\t\t        <div class=\"category-tab-summary\">\r\n");
      out.write("\t\t\t\t            <div class=\"text-group-category\">\r\n");
      out.write("\t\t\t\t                <div class=\"category-title\">Applications</div>\r\n");
      out.write("\t\t\t\t                <div class=\"category-desc\">\r\n");
      out.write("\t\t\t\t                    <div>Make, Create and Innovate.</div>\r\n");
      out.write("\t\t\t\t                </div>\r\n");
      out.write("\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t        <div class=\"service-list-background-container\">\r\n");
      out.write("\t\t\t\t            <div class=\"service-two-columns2\">\r\n");
      out.write("\t\t\t\t                <div class=\"service-summary2\">\r\n");
      out.write("\t\t\t\t                    <div class=\"text-group-service\">\r\n");
      out.write("\t\t\t\t                        <div class=\"service-title-preview-layout\">\r\n");
      out.write("\t\t\t\t                            <div class=\"service-name-summary-tab\" data-trackas=\"service-name-summary-tab\">        \r\n");
      out.write("\t\t\t\t                            \t<a id=\"btn_item1\" href=\"\">Analytics Builder</a>\r\n");
      out.write("\t\t\t\t                            </div>\r\n");
      out.write("\t\t\t\t                        </div>\r\n");
      out.write("\t\t\t\t                        <div class=\"service-title-summary-tab\">Provides statistical analytics framework make you to be a power users.</div>\r\n");
      out.write("\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t                </div>\r\n");
      out.write("\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t<!--\r\n");
      out.write("\t\t\t\t            <div class=\"service-two-columns2\">\r\n");
      out.write("\t\t\t\t                <div class=\"service-summary2\">\r\n");
      out.write("\t\t\t\t                    <div class=\"text-group-service\">\r\n");
      out.write("\t\t\t\t                        <div class=\"service-title-preview-layout\">\r\n");
      out.write("\t\t\t\t                            <div class=\"service-name-summary-tab\" data-trackas=\"service-name-summary-tab\">        \r\n");
      out.write("\t\t\t\t                            \t<a id=\"btn_item2\" href=\"\">Dashboard</a>\r\n");
      out.write("\t\t\t\t                            </div>\r\n");
      out.write("\t\t\t\t                        </div>\r\n");
      out.write("\t\t\t\t                        <div class=\"service-title-summary-tab\">Interactive dashboard with dynamic filtering.</div>\r\n");
      out.write("\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t                </div>\r\n");
      out.write("\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t\t\t\t<!--\r\n");
      out.write("\t\t\t\t            <div class=\"service-two-columns2\">\r\n");
      out.write("\t\t\t\t                <div class=\"service-summary2\">\r\n");
      out.write("\t\t\t\t                    <div class=\"text-group-service\">\r\n");
      out.write("\t\t\t\t                        <div class=\"service-title-preview-layout\">\r\n");
      out.write("\t\t\t\t                            <div class=\"service-name-summary-tab\" data-trackas=\"service-name-summary-tab\">        \r\n");
      out.write("\t\t\t\t                            \tMobile\r\n");
      out.write("\t\t\t\t                            </div>\r\n");
      out.write("\t\t\t\t                        </div>\r\n");
      out.write("\t\t\t\t                        <div class=\"service-title-summary-tab\">Standard Web3.0 Mobile Screen without furthur development. (Under Development)</div>\r\n");
      out.write("\t\t\t\t                    </div>\r\n");
      out.write("\t\t\t\t                </div>\r\n");
      out.write("\t\t\t\t            </div>\r\n");
      out.write("\t\t\t\t\t\t\t-->\r\n");
      out.write("\t\t\t\t        </div>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t         </div>\r\n");
      out.write("\t         <div class=\"column column-right with-copy\">\r\n");
      out.write("\t            <div class=\"copy text-left\">\r\n");
      out.write("\t               <h2 class=\"heading-headline\">\r\n");
      out.write("\t                  Click applications to work with\r\n");
      out.write("\t               </h2>\r\n");
      out.write("\t               <p class=\"section-body allow-orphan\">\r\n");
      out.write("\t                  Full web integration of Apache R statistical engine, and various visualization chart on single Business Analysis Framework. Build your report and view in dashboard without IT support.\r\n");
      out.write("\t               </p>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t         </div>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t   </div>\r\n");
      out.write("\t   \r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"maia-footer\" id=\"maia-footer\">\r\n");
      out.write("\t    <div id=\"maia-footer-global\">\r\n");
      out.write("\t        <div class=\"maia-aux\">\r\n");
      out.write("\t            <div class=\"maia-locales\">\r\n");
      out.write("\t                <label>\r\n");
      out.write("\t                    <select id=\"b_loc\">\r\n");
      out.write("\t                        <option selected=\"\" value=\"en_US\">English</option>\r\n");
      out.write("\t                        <option value=\"zh_CN\">Chinese Simplified</option>\r\n");
      out.write("\t                        <option value=\"zh_TW\">Chinese Traditional</option>\r\n");
      out.write("\t                        <option value=\"ja_JP\">Japanese</option>\r\n");
      out.write("\t                        <option value=\"ko_KR\">Korean</option>\r\n");
      out.write("\t                    </select>\r\n");
      out.write("\t                </label>\r\n");
      out.write("\t            </div>\r\n");
      out.write("\t            <ul>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <a href=\"/\">&copy; amplixbi.com All rights reserved.</a>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <a href=\"./about.html\">About amplix</a>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                    <a href=\"./policy.html\">Privacy &amp; Terms</a>\r\n");
      out.write("\t                </li>\r\n");
      out.write("\t            </ul>\r\n");
      out.write("\t        </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\r\n");
      out.write("  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\r\n");
      out.write("  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\r\n");
      out.write("  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');\r\n");
      out.write("\r\n");
      out.write("  ga('create', 'UA-110159277-1', 'auto');\r\n");
      out.write("  ga('send', 'pageview');\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
